### ISSUE TITLE
Add option to control level of rain

### ISSUE THREAD

**Issue by astratagem** [isdampe/music-for-programming#11]
rainymood.com has a button that allows the user to choose between a few different volume levels of rain. It would be cool to have that feature here.

**Comment by isdampe** [comment]
This kind of relates to #4, as the current audio output library we are relying on doesn't appear to support any kind of volume control

**Comment by isdampe** [comment]
Could probably use something like [pcm-volume](https://www.npmjs.com/package/pcm-volume) to do this.
