### ISSUE TITLE
Problems with Speaker on Sierra.

### ISSUE THREAD

**Issue by netyaroze** [isdampe/music-for-programming#12]
Hey There,

Seems if i try and switch to another podcast / pause - unpause the player i get the following:

[../deps/mpg123/src/output/coreaudio.c:81] warning: Didn't have any audio data in callback (buffer underflow)                                        
[1]    65156 illegal hardware instruction  

Assuming this is a problem with libmpg123 being old as heck?

Thanks!

**Comment by isdampe** [comment]
I don't have a machine running Sierra to confirm this, but I have experienced somewhat similar behaviour on Linux64 when toggling play/pause if I do it too quickly. Unsure if related issue, I'll do some digging if I get a chance

**Comment by scorchio** [comment]
This happens with toggling rain on/off as well.

**Comment by isdampe** [comment]
In 0.1.11, we switched to a wrapper-library `fat-mp3` that should help prevent this from happening. I believe this occurs if there is an intermittent or loss of network connection whilst streaming, and thus the request buffer that is piped to `lame` for decoding and then `speaker` for PCM output empties before PCM playback finishes.

A fix for this would be to build and insert a stream class right after the request pipe that automatically pauses when the buffer is emptied.

**Comment by netyaroze** [comment]
Cheers, works perfectly now :)
