### ISSUE TITLE
Access Denied even when running installation script with sudo

### ISSUE THREAD

**Issue by haykerman** [isdampe/music-for-programming#14]
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/music-for-programming/node_modules/lame/build'

**Comment by isdampe** [comment]
This is a permissions issue on your local system. You could try installing locally and executing by:

```bash
cd ~/
git clone https://github.com/isdampe/music-for-programming.git
cd music-for-programming
npm install
./mfp.js
```
